### PR TITLE
Adding FusionAuth identity server

### PR DESCRIPTION
**Pull request by mooreds**
Hiya!

Thought it'd be useful to add the FusionAuth identity server.

I added it to the security and privacy section, but wasn't sure if I should create a separate 'dev tools' section. Either way works for me.

### CODE REVIEW

**Comment by l4rm4nd** [comment]
Hi @mooreds,

thanks for your submission.

Not gonna lie, I will have to have a look into FusionAuth later. Never heard of it or used it. 

The [GitHub repos](https://github.com/fusionauth) seem not to be that popular too. So not sure how many people will benefit from adding a project that is not that relevant and also already provides the relevant compose files.

Guess I will refrain from adding it now, as it would be the first and only OICD/SSO/IAM container. Would rather add it into the mix if there are multiple options provided (such as authelia, authentik, etc.).

However, will definitely have a look into it.

**Comment by mooreds** [comment]
thanks for the feedback @l4rm4nd !

The docker file is pretty popular ( https://hub.docker.com/r/fusionauth/fusionauth-app has 10M+ downloads).

If I were to provide 1-2 others and put them all in a separate section, would you reconsider? Let me know if so. If not, totally get it.

**Comment by l4rm4nd** [comment]
Sure, maybe add some keycloak and authentik into the mix if you can.

Also try to align all compose files to use bind volume mounts. They are easier to backup and understand for beginners. 

May see the example skeleton.

I've added and implemented authelia in my infra yesterday. So the first category for IAM/SSO/2FA is available.

**Comment by l4rm4nd** [comment]
Sure, maybe add some keycloak and authentik into the mix if you can.

I've found this one: https://gitlab.desy.de/johannes.reppin/keycloak-docker-compose

Also try to align all compose files to use bind volume mounts. They are easier to backup and understand for beginners. 

May see the example skeleton.

I've added and implemented authelia in my infra yesterday. So the first category for IAM/SSO/2FA is available.

The general problem of such containers is the complexity. They must be combined with other things like a reverse proxy usually and highly depend on the end goal someone tries to achieve.

I just want to ensure that the provided examples 100% work and provide a benefit. For single containers, this is pretty easy. For more complex stuff it gets often messy. Just my thougts.

**Pull request closed without merging**
