### PR TITLE
Add a few apps

### PR DESCRIPTION
**Pull request by neu-ma-tic**
Hey, like the work you're doing here. I added a few services which I love. I'm not sure what the scope of the apps wanted are, but here are a few large apps, as well as Firefox.

### Apps
- Firefox
- Libreddit
- Nitter
- Invidious

I have a bit of free time; so what apps would be considered in-scope to be added to this list?

### CODE REVIEW

**Comment by l4rm4nd** [comment]
Hi @neu-ma-tic ,

many thanks for your contribution! 

The alternative frontends to various social media platforms look really cool. This is something I'd totally be fine adding to the repo. The most images by linuxserver.io come with pretty good documentation and compose ymls though. I would be fine to add firefox for now, as it is really popular. Otherwise, I'd focus on projects that do not provide a convenient docker-compose.yml file (e.g. only docker run commands or an incomplete compose file with no database and such).

Please adjust your commit again:

-  I've seen you created a bogus `firefox copy` folder. Can be removed, right?
- Please use the new volume mapping syntax. I've adjusted the general volume mappings to define an ENV for volume path customizations. See the skeleton example. You can now use `- ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/example:/opt/example/data`.
- Placing the alternative frontends to the category "Internet of Things" in the repo's readme is a bit weird imo. Please create a new category, e.g. `Alternative Frontends` or append them to `Security & Privacy` which makes sense too I guess.

**Comment by l4rm4nd** [comment]
I'll close the PR for now and will add your alternative frontends manually later. Just too many things to fix for now.

However, feel free to issue another PR with your adjustments.

**Comment by l4rm4nd** [comment]
I've added Firefox. See https://github.com/Haxxnet/Compose-Examples/commit/28d5e37906afba2a4c1eb1bbd0904fa92b668f0b

**Comment by l4rm4nd** [comment]
I've added Libreddit. See https://github.com/Haxxnet/Compose-Examples/commit/4ea25291c6efc341a11e053ca61f14f4bdd8e8a9

**Comment by neu-ma-tic** [comment]
Thanks, (and sorry for not responding either)

looks like i just fat-fingered some stuff when making it 🤓

**Pull request closed without merging**
